# Generated by Django 4.2.2 on 2023-09-27 23:56

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupings', '0003_alter_group_by_ad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=90)),
                ('seller_id', models.IntegerField()),
                ('category_id', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('sold_quantity', models.IntegerField()),
                ('listing_type_id', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('condition', models.CharField(max_length=30)),
                ('permalink', models.CharField(max_length=300)),
                ('shipping_type', models.CharField(max_length=30)),
                ('health', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('catalog_listing', models.BooleanField()),
                ('tracking_since', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingProduct',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=30)),
                ('image', models.ImageField(default='products_images/default.png', upload_to='products_images/')),
                ('title', models.CharField(max_length=60, null=True)),
                ('seller', models.IntegerField(null=True)),
                ('tracking_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_tracking_activated', models.BooleanField(default=True)),
                ('group', models.ManyToManyField(related_name='products', to='groupings.group_by_ad')),
                ('user', models.ManyToManyField(related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
