# Generated by Django 4.2.2 on 2023-09-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_group_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products_images/default.png', upload_to='products_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
