# Generated by Django 4.2.2 on 2023-08-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=15)),
                ('start_date', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
    ]
