# Generated by Django 4.2.2 on 2023-09-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_by_ad',
            name='image',
            field=models.ImageField(default='group_by_ad_images/default.png', upload_to='group_by_ad_images/'),
        ),
    ]
