# Generated by Django 3.0.3 on 2023-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
