# Generated by Django 4.2.2 on 2023-08-22 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupings', '0004_agrupamento_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupamento',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Agrupamento_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('start_date', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=15)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
