# Generated by Django 4.2.2 on 2023-08-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0005_agrupamento_seller_group_by_ad_delete_agrupamento'),
        ('groupings', '0005_alter_agrupamento_criador_agrupamento_seller'),
    ]

    operations = [
    ]
