# Generated by Django 4.2.2 on 2023-08-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_shipping',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='logistic_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
